#define WIFI_SSID "_braen"
#define WIFI_PASSWORD "1234567890"
  #define INFLUXDB_URL "https://us-east-1-1.aws.cloud2.influxdata.com"
  #define INFLUXDB_TOKEN "e-oQ0_uKvu0_vYipPxY4cas-Ae8Bh6V52U8_RU4PND0qJy9l_XKeO3SpHTFx9q0T-RxxyIfxYdKmjvRTtaDXlQ=="
  #define INFLUXDB_ORG "espVoltage"
  #define INFLUXDB_BUCKET "espVoltage1"
#define DEVICE "ESP"